### ISSUE TITLE
Cannot build with parcel

### ISSUE THREAD

**Issue by AaronAcerboni** [EreHuc/Tetra-Master-JS#6]
Hey this sounds looks like a cool project. I know it's probably collecting cob webs 🕸️ but...

I haven't been able to build and preview it using `npm run dev` as I think parcel fails with the following error:

```
PS C:\Users\Aaron\Desktop\Tetra-Master-JS> npm run dev

> tetra-master-js@0.0.1 dev C:\Users\Aaron\Desktop\Tetra-Master-JS
> parcel index.html

Server running at http://localhost:1234
×  C:\Users\Aaron\Desktop\Tetra-Master-JS\src\javascript\main.js: function __clone() {for package installation - must us
    var node2 = new Node();
    for (var key in this) {
      // Do not clone comments tha...<omitted>... } could not be cloned.
    var node2 = new Node();
    for (var key in this) {
      // Do not clone comments tha...<omitted>... } could not be cloned.
    at Object.serialize (v8.js:253:7)
    at _default (C:\Users\Aaron\Desktop\Tetra-Master-JS\node_modules\@babel\core\lib\transformation\util\clone-deep.js:22:34)
    at normalizeFile (C:\Users\Aaron\Desktop\Tetra-Master-JS\node_modules\@babel\core\lib\transformation\normalize-file.js:84:36)
    at normalizeFile.next (<anonymous>)
    at run (C:\Users\Aaron\Desktop\Tetra-Master-JS\node_modules\@babel\core\lib\transformation\index.js:29:50)
    at run.next (<anonymous>)
    at Function.<anonymous> (C:\Users\Aaron\Desktop\Tetra-Master-JS\node_modules\@babel\core\lib\transform-ast.js:26:41)
    at Generator.next (<anonymous>)
    at evaluateSync (C:\Users\Aaron\Desktop\Tetra-Master-JS\node_modules\gensync\index.js:251:28)
    at Function.sync (C:\Users\Aaron\Desktop\Tetra-Master-JS\node_modules\gensync\index.js:89:14)
```

I suspect it's a version issue? Would it be possible to add a `dist` folder with prebuilt html files with the tetra master game?

**Comment by colinbellino** [comment]
Hey there, i'm not the maintainer but i saw this issue pop in my emails :P
I think you should be able to grab the dist files from here: https://tetra-master-js.appspot.com (though it is in a minified form)

**Comment by EreHuc** [comment]
Hi ! Old project here indeed and some of the dependencies I use don't respect semver and introduce some breaking change. I fix the dependencies version I used when I work on the project.
Don't look to closer to the code, I made it few years ago to improve my dev skill :P
